### ISSUE TITLE
`processRow` approach with submodule has bad form

### ISSUE THREAD

**Issue by m-walters** [ArthurHeitmann/arctic_shift#15]
Both asking to install the repo as a submodule and then telling users to edit the `processRow` function inside `processFiles.py` I think is bad form. We shouldn't be editing submodule code really. Consider:
- As a submodule we want users to use and import the `processFile` and `processFolder` utils.
- We should remove the `processRow` and its call in those utils. Instead, the utils should _accept_ a `processRow` callable as an argument.
- That way users can define their processRow callable and pass it in.

**Comment by m-walters** [comment]
I guess this contradicts the intention of the `processFiles.py` as a script, and would entail refactoring things to provide `utils` for users basically. idk, your call if interested in that.

**Comment by ArthurHeitmann** [comment]
I'm not quite sure what you mean. processFiles.py is a main file and not a submodule.

Regardless though, the file isn't meant to be a one size fits all solution. It's mostly just a starting point, so that people are introduced to the stream based file reading and don't try to decompress all files in memory or to disk.

If you have suggestions on how to simplify it or make it easier to understand, let me know.

**Comment by m-walters** [comment]
Oh hey @ArthurHeitmann, I didn't notice you responded day of, sorry!
Basically, your documentation recommends users install this as a git submodule and then edit that code -- but it's bad form/practice to edit submodules. They should really be treated as standalone dependencies basically.

So I was describing something like allowing users to pass in their own callable so that they don't have to edit the submodule code.
But really, the quickest route here is to just tell users to just `git clone` this repo and use it as its own thing, and not to `submodule` within their own repos.

**Comment by ArthurHeitmann** [comment]
Ah, I see now what your criticism was. You want to use this repository as a sort of library, that you can embed into any other project. But that was not the intention of the repo. That's why for example there are a lot of documentation files here.

A library would maybe be nice, but the question is whether that is really needed. There is not much code wise going on here. Technically all you need to process a file is:
1. a line reader
2. zstd decompression library
3. json parser

**Comment by m-walters** [comment]
oh my apologies, you wrote `Clone this repository and its submodules` in the docs, not 'clone _as_ a submodule', all good
