### ISSUE TITLE
Connecting comments to submissions 

### ISSUE THREAD

**Issue by DavidHerel** [ArthurHeitmann/arctic_shift#5]
Hi,

I have noticed you split comments and submissions. Is there any script available that can connect comments to each submission? Also, comment ordering, where you can see the hierarchy of replies would be beneficial. 

Thanks for the reply!

**Comment by ArthurHeitmann** [comment]
Hi, they are separated because they are archived as they are posted, and appended to a file, one by one. Reconstructing the comment trees for hundreds of gigabytes of data, would be a bit too much.

But you can link them yourself, for smaller numbers. Each post and comment has a `"name"` (or `"id"`, but without prefix). And each comment also has `"link_id"` (`"name"` of the submission that this comment belongs to) and `"parent_id"`. The `"parent_id"` is either the `"name"` of the parent comment, or if it's a top level comment, it's the `"name"` of the submission.
